//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstoricApeluri
    {
        public int Id { get; set; }
        public string NrTelefon { get; set; }
        public Nullable<System.DateTime> DataSiOra { get; set; }
        public Nullable<int> Durata { get; set; }
        public Nullable<bool> Ptimit { get; set; }
    
        public virtual Agendum Agendum { get; set; }
    }
}
