USE AgendaTelefonica

ALTER TABLE	[Agenda] ALTER COLUMN [NrTelefon] VARCHAR(10) NOT NULL;
ALTER TABLE	[IstoricApeluri] ALTER COLUMN [NrTelefon] VARCHAR(10) NOT NULL;


ALTER TABLE	[Agenda] ALTER COLUMN [Nume] VARCHAR(255) NOT NULL;
ALTER TABLE	[Agenda] ALTER COLUMN [Prenume] VARCHAR(255) NOT NULL;
ALTER TABLE	[Agenda] ALTER COLUMN [DataNasterii] DateTime NOT NULL;
ALTER TABLE	[Agenda] ALTER COLUMN [Stat] VARCHAR(2) NOT NULL;

ALTER TABLE	[IstoricApeluri] ALTER COLUMN [Id] int NOT NULL;
ALTER TABLE	[IstoricApeluri] ALTER COLUMN [DataSiOra] DateTime NOT NULL;
ALTER TABLE	[IstoricApeluri] ALTER COLUMN [Durata] int NOT NULL;
ALTER TABLE	[IstoricApeluri] ALTER COLUMN [Primit] bit NOT NULL;


